drop table models_medline_citation_cited_in__models_medline_citation;
drop table models_medline_citation_authors__models_medline_author_citations;
drop table models_medline_citation_languages__models_medline_language;
drop table models_medline_citation_pub_types__models_medline_pubtype;
drop table pub_type_citation;
drop table lan_cit                                                         ;
drop table models_medline_subheadingterm                                   ;
drop table models_medline_citation_meshterms__models_medline_termcitation;
drop table models_medline_termcitation;
drop table models_medline_citation;
