#!/bin/sh
dir=$(dirname $0)
for f in "$@"; do
	python2 $dir/json2pickle.py --json "$f" --pickle "$f.pickle" &&
	python2 $dir/pickle2edgelist.py --pickle "$f.pickle" > "$f.edgelist" &&
	rm "$f.pickle"
done
