from elixir import *
from models.medline import *
from random import shuffle

metadata.bind = 'mysql+oursql://caopsci:G@localhost/medline'

setup_all()

roots = {
    'A': 'Anatomy',
    'B': 'Organisms',
    'C': 'Diseases',
    'D': 'Chemical and Drugs',
    'E': 'Analytical, Diagnostic and Therapeutic Techniques and Equipment',
    'F': 'Psychiatry and Psychology',
    'G': 'Biological Sciences',
    'H': 'Natural Sciences',
    'I': 'Anthropology, Education, Sociology and Social Phenomena',
    'J': 'Technology, Industry, Agriculture',
    'K': 'Humanities',
    'L': 'Information Science',
    'M': 'Named Groups',
    'N': 'Health Care',
    'V': 'Publication Characteristics',
    'Z': 'Geographic Locations',
}



colors = ['white',
'vvvvlgrey',
'vvvlgrey',
'vvlgrey',
'vlgrey',
'lgrey',
'grey',
'dgrey',
'vdgrey',
'vvdgrey',
'vvvdgrey',
'vvvvdgrey',
'black',
'transparent',
'vvlred',
'vlred',
'lred',
'red',
'dred',
'vdred',
'vvdred',
'vvlpred',
'vlpred',
'lpred',
'pred',
'dpred',
'vdpred',
'vvdpred',
'vvlgreen',
'vlgreen',
'lgreen',
'green',
'dgreen',
'vdgreen',
'vvdgreen',
'vvlpgreen',
'vlpgreen',
'lpgreen',
'pgreen',
'dpgreen',
'vdpgreen',
'vvdpgreen',
'vvlblue',
'vlblue',
'lblue',
'blue',
'dblue',
'vdblue',
'vvdblue',
'vvlpblue',
'vlpblue',
'lpblue',
'pblue',
'dpblue',
'vdpblue',
'vvdpblue',
'vvlpurple',
'vlpurple',
'lpurple',
'purple',
'dpurple',
'vdpurple',
'vvdpurple',
'vvlppurple',
'vlppurple',
'lppurple',
'ppurple',
'dppurple',
'vdppurple',
'vvdppurple',
'vvlorange',
'vlorange',
'lorange',
'orange',
'dorange',
'vdorange',
'vvdorange',
'vvlporange',
'vlporange',
'lporange',
'porange',
'dporange',
'vdporange',
'vvdporange',
'vvlyellow',
'vlyellow',
'lyellow',
'yellow',
'dyellow',
'vdyellow',
'vvdyellow',
'vvlpyellow',
'vlpyellow',
'lpyellow',
'pyellow',
'dpyellow',
'vdpyellow',
'vvdpyellow',]
shuffle(colors)

for letter in roots:
    chrom = Branch.query.filter(Branch.branch.like(letter+'%'))    
    #      chr - ID LABEL START END COLOR
    print "chr - %s %s    %s    %s  %s" % ( letter,
                                            letter,
                                            chrom[0].id,
                                            chrom[-1].id,
                                            colors.pop()
                                            )
                                            
